# Generated by Django 5.0.7 on 2024-08-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
