# Generated by Django 5.0.7 on 2024-08-16 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='atribute',
        ),
        migrations.RemoveField(
            model_name='key',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_list',
        ),
        migrations.RemoveField(
            model_name='product',
            name='primary_image',
        ),
        migrations.RemoveField(
            model_name='value',
            name='atribute',
        ),
        migrations.RemoveField(
            model_name='value',
            name='slug',
        ),
        migrations.AlterField(
            model_name='atribute',
            name='key_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olcha.key'),
        ),
        migrations.AlterField(
            model_name='atribute',
            name='value_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olcha.value'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='olcha.product')),
            ],
        ),
    ]
