# Generated by Django 5.0.7 on 2024-08-16 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0002_remove_key_atribute_remove_key_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='olcha.group'),
            preserve_default=False,
        ),
    ]
